[package]
name = "day09b"
version = "0.1.0"
authors = ["Tim Visee <3a4fb3964f@sinenomine.email>"]
edition = "2021"
default-run = "day08b"

[lib]
path = "src/main.rs"

[dependencies]
atoi = "2.0"
lending-iterator = "0.1"
smallvec = { version = "1.11", features = ["const_generics", "const_new"] }
